import Head from 'next/head';
import Header from '../components/Header';
import Hero from '../components/Hero';
import About from '../components/About';
import Skills from '../components/Skills';
import Work from '../components/Work';
import Contact from '../components/Contact';
import CallToAction from '../components/CallToAction';
import Footer from '../components/Footer';

export default function Home() {
  return (
    <div className="font-sans bg-black text-slate-200 h-screen z-0 overflow-y-scroll overflow-x-hidden scroll-smooth scrollbar-firefox md:scrollbar">
      <Head>
        <title>Kyle Tang</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>

      <Header />

      <main>
        <Hero />

        <About />

        <CallToAction />

        <Skills />

        <Work />

        <Contact />
      </main>

      <Footer />
    </div>
  );
}
