import Head from 'next/head';
import Header from '../components/Header';
import { Open_Sans, Montserrat } from '@next/font/google'

const open_sans = Open_Sans({ weight: '400' });
const monsterrat = Montserrat({ weight: '400' });

export default function Home() {
  return (
    <div className={`${open_sans.className} bg-slate-900 text-slate-200 h-screen`}>
      <Head>
        <title>Kyle Tang</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}

      <Header />

      <main>

        {/* Hero */}

        {/* About */}

        {/* Skills */}

        {/* Work */}

        {/* Contact */}

      </main>

      {/* Footer */}
    </div>
  )
}
